### ISSUE TITLE
Creación de Pruebas Unitarias para Funciones de Gestión de Productos

### ISSUE THREAD

**Issue by Yennyferjp** [Yennyferjp/Burger-Queen-App#16]
En este issue, se aborda la tarea de crear pruebas unitarias exhaustivas para cada una de las funciones que gestionan productos en nuestra aplicación. Cada función, incluyendo las operaciones GET, POST, PATCH y DELETE,  asegurandonos que todas las funciones relacionadas con productos respondan de manera adecuada a diferentes escenarios, incluyendo datos válidos e inválidos, y manejen errores de manera apropiada

**Comment by LeslieGaribay** [comment]
Tests para las funciones:

- [ ] getProducts
- [ ] addProduct
- [ ] getProduct
- [ ] updateProduct
- [ ] deleteProduct
