### ISSUE TITLE
Crear la configuración Inicial

### ISSUE THREAD

**Issue by Yennyferjp** [Yennyferjp/Burger-Queen-App#2]
Configurar el proyecto con la estructura básica.
Configurar enrutamiento básico.

**Comment by LeslieGaribay** [comment]
- [ ] Forks de los repositorios
- [ ] Vinculación repositorios frontend y backend
- [ ] Creación de boilerplate de repositorio frontend
- [ ] Instalación de dependencias
- [ ] Instalación de puerto 8080
- [ ] Configuración de package.json
- [ ] Configurar enrutamiento básico
