### ISSUE TITLE
Accionables de aprendizaje tech

### ISSUE THREAD

**Issue by Yennyferjp** [Yennyferjp/Burger-Queen-App#34]
- Dominar la librería de React, considero profundizar en el desarrollo web .Ya que es una libreria muy utilizada en la industria y asi poder adquirir habilidades en el desarrollo de aplicaciones web más avanzadas. Realizar proyectos personales o cursos relacionados para adquirir experiencia en el uso de React.

- Aprender de Backend y Bases de Datos: Dado que he trabajado principalmente en el frontend, podría ser beneficioso aprender sobre desarrollo de backend. Explorar más Node.js, Express.js y bases de datos como MongoDB o PostgreSQL. Esto te permitirá crear aplicaciones web completas y comprender cómo funcionan tanto el frontend como el backend.

- Optimización de Proyectos BC: Dedicaré tiempo a revisar y optimizar los proyectos que realicé durante el bootcamp. Mejoraré el código, la estructura y la documentación.  Además, consideraré la posibilidad de implementar nuevas características o funcionalidades en estos proyectos para ampliar mi experiencia y tener un buen portafolio.

**Comment by icarito** [comment]
* [ ] Terminar de implementar este proyecto (también tests)
* [ ] Inspírate y realiza un proyecto que sea de tu propio interés (y publícala en github)
* [ ] Sugerencia: Intenta usar o probar un sistema operativo libre, como Ubuntu o Manjaro (Linux)
* [ ] Revisa algún otro proyecto de Laboratoria e intenta implementarlo! Fleet management, por ejemplo, para backend.
